#!/usr/bin/env python3
"""Generate a blue-noise threshold matrix via the void-and-cluster algorithm
(Ulichney 1993) and emit it as a C header for ordered dithering.

The matrix is tileable (filtering uses wrap-around), so indexing it with
(x & (N-1), y & (N-1)) gives a seamless blue-noise threshold field with no
visible grid pattern — unlike a Bayer matrix.

Output: lib/GfxRenderer/BlueNoise.h  (N x N, values 0..255)
Shared by the EPUB image converters and the Bitmap (sleep/viewer) renderer.

Run manually when changing N; the result is committed (not a build step).
"""
import numpy as np
from scipy.ndimage import gaussian_filter

N = 64                # matrix size (tileable). 64x64 = 4 KB flash.
SIGMA = 1.9           # gaussian energy spread (standard void-and-cluster value)
SEED = 1


def filtered(binary):
    # Wrap-around gaussian so the matrix tiles seamlessly.
    return gaussian_filter(binary.astype(np.float64), SIGMA, mode="wrap")


def tightest_cluster(binary):
    e = filtered(binary)
    e[binary == 0] = -np.inf      # only consider 1s
    return np.unravel_index(np.argmax(e), e.shape)


def largest_void(binary):
    e = filtered(binary)
    e[binary == 1] = np.inf       # only consider 0s
    return np.unravel_index(np.argmin(e), e.shape)


def main():
    rng = np.random.default_rng(SEED)
    binary = np.zeros((N, N), dtype=np.uint8)

    # Initial pattern: ~10% random points.
    n_init = (N * N) // 10
    idx = rng.choice(N * N, n_init, replace=False)
    binary.flat[idx] = 1

    # Phase 0: make the initial pattern a "prototype" blue-noise binary pattern
    # by repeatedly moving the tightest cluster point into the largest void.
    while True:
        c = tightest_cluster(binary)
        binary[c] = 0
        v = largest_void(binary)
        if v == c:
            binary[c] = 1
            break
        binary[v] = 1

    rank = np.full((N, N), -1, dtype=np.int32)
    ones = int(binary.sum())

    # Phase 1: rank existing points by removing tightest clusters (high->low).
    work = binary.copy()
    for r in range(ones - 1, -1, -1):
        c = tightest_cluster(work)
        work[c] = 0
        rank[c] = r

    # Phase 2: rank remaining points by filling largest voids.
    work = binary.copy()
    for r in range(ones, N * N):
        v = largest_void(work)
        work[v] = 1
        rank[v] = r

    # Normalize rank 0..N*N-1 to threshold 0..255.
    thr = np.round(rank.astype(np.float64) * 255.0 / (N * N - 1)).astype(np.uint8)

    out = []
    out.append("#pragma once")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"// {N}x{N} blue-noise threshold matrix (void-and-cluster, tileable).")
    out.append("// Generated by scripts/gen_bluenoise.py — do not edit by hand.")
    out.append("// Index with (x & %d, y & %d); dither white when gray > value." % (N - 1, N - 1))
    out.append(f"inline const uint8_t blueNoise{N}[{N}][{N}] = {{")
    for y in range(N):
        row = ", ".join(str(int(v)) for v in thr[y])
        out.append(f"    {{{row}}},")
    out.append("};")
    out.append("")

    path = "lib/GfxRenderer/BlueNoise.h"
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {path} ({N}x{N})")


if __name__ == "__main__":
    main()
